export const ADD_DOCUMENT='ADD_DOCUMENT';
export const ADD_DOCUMENT_ERROR='ADD_DOCUMENT_ERROR';
export const UPDATE_SKIN_CODE='UPDATE_SKIN_CODE';
export const UPDATE_SKIN_CODE_ERROR='UPDATE_SKIN_CODE_ERROR';

export const ADD_CONTACT = "ADD_CONTACT";
export const ADD_CONTACT_ERROR = "ADD_CONTACT_ERROR";
export const UPDATE_CONTACT = "UPDATE_CONTACT";
export const UPDATE_CONTACT_ERROR = "UPDATE_CONTACT_ERROR";

export const ADD_EDUCATION = "ADD_EDUCATION";
export const ADD_EDUCATION_ERROR = "ADD_EDUCATION_ERROR";
export const UPDATE_EDUCATION = "UPDATE_EDUCATION";
export const UPDATE_EDUCATION_ERROR = "UPDATE_EDUCATION_ERROR";

export const ADD_FINALIZE='ADD_FINALIZE';
export const ADD_FINALIZE_ERROR='ADD_FINALIZE_ERROR';
export const UPDATE_FINALIZE='UPDATE_FINALIZE';
export const UPDATE_FINALIZE_ERROR='UPDATE_FINALIZE_ERROR';
export const CHANGE_FONT_SIZE ="CHANGE_FONT_SIZE";
export const CHANGE_FONT_FAMILY ="CHANGE_FONT_FAMILY";



export const REGISTER = "REGISTER";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const SIGN_IN ="SIGN_IN";
export const SIGN_IN_FAILED ="SIGN_IN_FAILED";
export const SIGN_OUT ="SIGN_OUT";
export const SIGN_OUT_FAILED ="SIGN_OUT_FAILED";


